#pragma once

enum TokenTypesE
{
  TKN_OPEN_CURLY_BRACKET,
  TKN_CLOSE_CURLY_BRACKET,
  TKN_OPEN_PARENTHESIS,
  TKN_CLOSE_PARENTHESIS,
  TKN_SEMICOLON,
  TKN_KEYWORD,
  TKN_IDENTIFIER,
  TKN_ARITH_OP,
  TKN_INTEGER,
  TKN_PLUS,
  TKN_MINUS,
  TKN_STAR,
  TKN_SLASH,
  TKN_NO_SECOND_TYPE
};